In [1]:
import pandas as pd
import altair as alt

census_df = pd.read_csv('CleanedCharlestownCensusData_WithFamilyCounts.csv')

census_df['Occupation'].value_counts().head(12)

Widow              88
Enslaved           33
Sea captain        13
Baker              13
Leather dresser    11
Cooper              8
Blacksmith          8
Housewright         8
Hatter              7
Chaise maker        6
Mariner             6
Cordwainer          6
Name: Occupation, dtype: int64

In [2]:
census_df = census_df.loc[(census_df["Occupation"] == "Sea captain") | (census_df["Occupation"] == "Baker") | (census_df["Occupation"] == "Leather dresser") | (census_df["Occupation"] == "Cooper") | (census_df["Occupation"] == "Blacksmith") | (census_df["Occupation"] == "Housewright") | (census_df["Occupation"] == "Hatter") | (census_df["Occupation"] == "Chaise maker") | (census_df["Occupation"] == "Mariner") | (census_df["Occupation"] == "Cordwainer")]
census_df.head()

,Order,Family,Original order,Link to Claim,Last Name,Maiden Name,First Name,Relation to Head of Household,Number of Family Members (Including Head),Age,Sex,Race,Occupation,Household Inventory # n=420,1375 people,Household,Family Notes
10,50,RES.030,51.0,Link to Claim Images,Barber,NaN,William,Head,9,?,M,W,Sea captain,23,9.0,"William Barber (?), Anne Hay (?), Abigain (20)...",Edward shot by troops at Charlestown Neck foll...
11,60,NaN,NaN,NaN,Barker,NaN,Barnabas,Father,3,?,M,W,Housewright,24,NaN,NaN,NaN
12,76,RES.035,82.0,No Claim Found,Beal,NaN,Joshua,Head,2,?,M,W,Sea captain,28,2.0,"Joshua Beal (?), Hannah Howard (?)",NaN
16,115,RES.044,132.0,Link to Claim Images,Bradish,NaN,James,Head,2,52,M,W,Blacksmith,37,1.0,"James Bradish (52), Mary Sterns (46)",NaN
17,117,RES.045,133.0,Link to Claim Images,Bradish,NaN,James,Head,2,66,M,W,Blacksmith,38,2.0,"James Bradish (66), Sarah Kettell (38),",NaN

In [3]:
occupations = census_df['Occupation'].unique()
colors = ['#77AADD', '#99DDFF', '#44BB99', '#BBCC33', '#AAAA00', '#EEDD88', '#EE8866', '#FFAABB', '#555555', '#CC6677']
occupations

array(['Sea captain', 'Housewright', 'Blacksmith', 'Chaise maker',
       'Cooper', 'Baker', 'Cordwainer', 'Leather dresser', 'Hatter',
       'Mariner'], dtype=object)

In [4]:
census_chart = alt.Chart(census_df, title="Distribution of Family Size per Worker in an Occupation (10 most common occupations)").mark_boxplot(opacity=0.75).encode(
    x=alt.X("Occupation"),
    y="Number of Family Members (Including Head):Q",
    color=alt.Color('Occupation:N', scale=alt.Scale(domain=occupations, range=colors))
    
).properties(
    width=450,
    height=250
)



avg_chart = alt.Chart(census_df, title="Average Family Size per Worker in an Occupation (10 most common occupations)").mark_bar(opacity=0.75, color='red').encode(
    x=alt.X("Occupation:N"),
    y="average(Number of Family Members (Including Head))",
    color=alt.Color('Occupation:N', scale=alt.Scale(domain=occupations, range=colors))
    
).properties(
    width=450,
    height=250
)



census_chart & avg_chart

alt.VConcatChart(...)